name: new_workflow

  
on:
  pull_request:
    branches: 
      - main
    types: [closed]

  
jobs:
  artia_comment_job:
    runs-on: ubuntu-latest
    name: Comment Activity.
    steps:
      - name: Comentando Atividade
        id: comment
        uses: mobral-inc/criar-comentario-por-pull-request@v1.1.3
        with: 
          organizationId: ${{ secrets.BOT_ARTIA_ORG_ID }}
          creatorEmail: ${{ secrets.BOT_ARTIA_EMAIL }}
          creatorPassword: ${{ secrets.BOT_ARTIA_PASSWORD }}
